### ISSUE TITLE
Read Multiple Section Clusters or Modified Section Clusters

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/Instrument-Framework#32]
https://github.com/levylabpitt/AFM-Lithography/issues/16#issuecomment-780109581
https://github.com/levylabpitt/AFM-Lithography/issues/16#issuecomment-780122280
https://github.com/levylabpitt/AFM-Lithography/issues/16#issuecomment-780195806
So I thought about the scenarios that we could have pertaining to the issue that I had in the other project and laid out what I thought would be the best way to go about this.
![image](https://user-images.githubusercontent.com/37567672/108260247-1931e000-7130-11eb-9f19-94cbaa04017b.png)

Replacing the default data with the existing data from file when the cluster size has grown (ie the section is missing an element) was complicated greatly by the fact that the returned data from the read ini file VIs does not have labelled elements. 
Here is the test setup that I did:
1. I created a file and initialized it with the following content:
```
[Test Cluster]
Hello = "World"
Number = "1"
Number 2 = "3"
```
2. Then I requested that it read from the file a cluster containing 1 more element than what was in the file. To make sure that the variant to data wasn't coercing the data I changed the values in the type cluster before I used it in variant to data:
![image](https://user-images.githubusercontent.com/37567672/108265227-80529300-7136-11eb-99e4-467f9efe8849.png)

3. This is what I came up with that correctly wrote to the file and returned the correct values:
![image](https://user-images.githubusercontent.com/37567672/108265657-0e2e7e00-7137-11eb-8703-38f9ab3d9a0b.png)
And the file contents:
![image](https://user-images.githubusercontent.com/37567672/108265747-2e5e3d00-7137-11eb-968e-dd6209cd29d7.png)
returned data:
![image](https://user-images.githubusercontent.com/37567672/108265816-48981b00-7137-11eb-8efe-66c0159de1ba.png)

Files:
[Configuration Prototype.zip](https://github.com/levylabpitt/Instrument-Framework/files/5998533/Configuration.Prototype.zip)

**Comment by ciozi137** [comment]
@Monkeymerlot thanks I will think about this. After first read can we just test if variant is empty?

**Comment by Monkeymerlot** [comment]
@ciozi137 Good question. I will check but I have a suspicion that it will return something like this:
```
" " =
" " =
" " =
```
Also I think that the fact that there are no names on the returned cluster is actually a bug in the openG VIs. I am thinking of opening an issue and doing a pull request with the fix (I fixed it on my machine already) but there are pull requests from 2013 that haven't been reviewed or merged yet so IDK if it will do any good.

**Comment by ciozi137** [comment]
@Monkeymerlot  I had to do a quick security update related to instrument/postgreSQL. I can look at the config stuff now.

**Comment by Monkeymerlot** [comment]
So testing for an empty variant will not work.
Without my fix for the variant configuration palette:
![image](https://user-images.githubusercontent.com/37567672/109028315-abd20200-768f-11eb-8e10-87cfaa3aa73a.png)
With Fix:
![image](https://user-images.githubusercontent.com/37567672/109028568-ed62ad00-768f-11eb-8101-6260a92dfaf0.png)
and test VI:
![image](https://user-images.githubusercontent.com/37567672/109028725-18e59780-7690-11eb-9da6-8f2425b0300a.png)

**Comment by ciozi137** [comment]
@Monkeymerlot thanks for checking. I also just checked and the result was that my config file was erased completely. I am going to take your zip file above and merge

**Comment by ciozi137** [comment]
@Monkeymerlot looking good. Update will be included in next build (1.8.3 I think)

Here is my test:
<img width="1465" alt="Screen Shot 2021-02-24 at 12 27 52 PM" src="https://user-images.githubusercontent.com/26659428/109040335-c90ccd80-769b-11eb-9aa9-881215f34347.png">

**Comment by Monkeymerlot** [comment]
The test looks good but I think you might have to delete the temp file once youre done with it.

**Comment by ciozi137** [comment]
@Monkeymerlot I delete it at the beginning of the test

**Comment by Monkeymerlot** [comment]
Oops missed that

**Comment by Monkeymerlot** [comment]
I was having some issues getting everything to work because it was looking for the Configuration Prototype file, but it was also not part of the class. So I put it in the class then deleted it from the project and pushed the changes. Hopefully that will fix it.

**Comment by ciozi137** [comment]
@Monkeymerlot no I took your code and added it to my VIs. So just update the instrument framework on vipm

**Comment by Monkeymerlot** [comment]
@ciozi137 I understand. I'm saying the project was looking for it probably when you had it open to copy the code. Like a ghost dependency. And it was making the class have a broken run arrow. It should be good now though.

**Comment by Monkeymerlot** [comment]
@ciozi137 I am not seeing a new package (current package is 1.7.0.95). Were you saying that you wanted me to build the package or did you not get to it yet or is there a problem on my end?

**Comment by ciozi137** [comment]
@Monkeymerlot refresh the repo. Latest version is 1.8.3

**Comment by Monkeymerlot** [comment]
@ciozi137 That was the issue \*slaps forehead\*. Thanks

**Comment by ciozi137** [comment]
@Monkeymerlot I just reverted your commit. Instrument Framework is programmed in LV2016 and you should be installing via VIPM. Can you elaborate what issue you were having with dependencies? I have no issue on my system

**Comment by ciozi137** [comment]
@Monkeymerlot sorry I see the problem now. I will build a new version (will be v1.8.3.100)

**Comment by Monkeymerlot** [comment]
No worries. LabVIEW just loves bringing us back to dependency hell...

**Comment by ciozi137** [comment]
bump
