### ISSUE TITLE
Could not install Package with VIPM

### ISSUE THREAD

**Issue by laserengineer** [levylabpitt/Instrument-Framework#33]
Hi there, 
Is the LevyLab Instrument Project installation file still available with VIPM?
Could not find the corrent VIPM file to install including the "build support" folder. 
![Leavy lab missing](https://user-images.githubusercontent.com/24920510/117890240-097af100-b272-11eb-88c7-e97f874dbc68.PNG)
Could you please advise the link for VI package to install?

**Comment by ciozi137** [comment]
@laserengineer you can follow the instructions [here ](https://levylabpitt.github.io)to add the package repository to VIPM.
